apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fe-be-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-k8s-manifests.git'  # Replace with actual repo
    targetRevision: HEAD
    path: k8s-manifests  # Path to your YAML files
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fe-be-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true