apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort # No need to use LB OR BROWSE THE APPLICATION 
  ports:
    - port: 5002
      targetPort: 5002
  selector:
    app: fe